# Este flujo de trabajo realizará una instalación limpia de las dependencias de Node, las almacenará en caché/restaurará, construirá el código fuente y ejecutará pruebas en diferentes versiones de Node
# Para obtener más información, consulta: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: windows-latest    

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'        
      - run: npm install
      - run: npm run update-readme     
      - name: Add safe directory exception
        run: git config --global --add safe.directory /github/workspace
      - run: |
          git config user.name jotalexvalencia
          git config user.email jorgealexandervalencia@gmail.com
          git remote add origin_with_token https://${{ secrets.GH_PAT }}@github.com/jotalexvalencia/jotalexvalencia.git
          git add README.md
          git commit -m "[bot] Update README with latest information"
          git push origin_with_token
