# Este es un flujo de trabajo (workflow) de GitHub Actions.
# Se ejecuta automáticamente o manualmente para actualizar el README.md con artículos recientes.

# Nombre del flujo de trabajo
name: Update README with Articles

# Cuándo se ejecutará:
on:
  # Se ejecuta semanalmente los lunes a medianoche UTC
  schedule:
    - cron: "0 0 * * 1"  # Formato cron: minuto hora día_del_mes mes día_de_la_semana (0=Domingo, 1=Lunes)

  # También permite ejecutarlo manualmente desde la pestaña "Actions" en GitHub
  workflow_dispatch:

# Permisos necesarios
permissions:
  # Solo necesita permiso para escribir contenido en el repositorio
  contents: write

# Definición de trabajos (jobs)
jobs:
  # Trabajo principal: update_readme_job
  update_readme_job:
    # Sistema donde se ejecutará: Ubuntu más reciente
    runs-on: ubuntu-latest

    # Pasos que realizará el trabajo
    steps:
      # Paso 1: Descargar código del repositorio
      - name: Check out repository code
        uses: actions/checkout@v4  # Acción oficial de GitHub para clonar el repo

      # Paso 2: Configurar entorno de Python
      - name: Set up Python environment
        uses: actions/setup-python@v5  # Versión recomendada de la acción
        with:
          python-version: '3.x'  # Usamos la última versión estable de Python

      # Paso 3: Instalar dependencias de Python
      - name: Install Python dependencies
        run: |
          # Actualiza pip (gestor de paquetes de Python) a la última versión
          python -m pip install --upgrade pip

          # Instala las bibliotecas listadas en requirements.txt
          # Asegúrate de tener este archivo en la raíz de tu proyecto
          pip install -r requirements.txt

      # Paso 4: Ejecutar el script Python que actualiza el README.md
      - name: Run script to update README.md
        run: |
          # Llama al script Python que obtiene artículos y modifica el README
          python update_readme.py

      # Paso 5: Hacer commit y push si hay cambios en README.md
      - name: Commit and push changes if README.md was modified
        shell: bash  # Usamos bash porque estamos en un sistema Linux (Ubuntu)
        run: |
          # Configura Git con tus datos personales
          git config --global user.name jotalexvalencia
          git config --global user.email jorgealexandervalencia@gmail.com

          # Verifica si hay cambios en README.md
          if [[ -z $(git status --porcelain README.md) ]]; then
            echo "No changes detected in README.md. Nothing to commit."
          else
            echo "Changes detected in README.md. Proceeding with commit and push..."

            # Prepara los cambios para hacer commit
            git add README.md

            # Crea un commit con los cambios
            git commit -m "chore: [bot] Update articles in README.md"

            # Configura la URL remota del repositorio con token de seguridad
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jotalexvalencia/jotalexvalencia.git

            # Sube los cambios a tu rama (ej. main o master)
            git push origin HEAD:${{ github.ref_name }}

            # Confirma que los cambios se subieron exitosamente
            echo "README.md committed and pushed successfully."
          fi

      # Paso Opcional: Notificar si falla el flujo
      - name: Notify on failure
        if: failure()  # Este paso solo ocurre si otro paso anterior falló
        run: |
          echo "El flujo de trabajo falló al actualizar el README."
          echo "Revisa los logs para ver qué salió mal."
